# Generated by Django 5.0.2 on 2024-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants_data',
            name='restaurant_password',
            field=models.CharField(max_length=20),
        ),
    ]
