# Generated by Django 5.0.2 on 2024-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0002_alter_restaurants_data_restaurant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=30)),
                ('cuisine_image', models.ImageField(upload_to='uploads')),
                ('cuisine_description', models.CharField(max_length=500)),
                ('cuisine_price', models.BigIntegerField()),
                ('cuisine_restaurant_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tables_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_accomodation_type', models.IntegerField()),
                ('table_status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='restaurants_data',
            name='restaurant_active_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='restaurants_data',
            name='restaurant_price_approx',
            field=models.CharField(default='1200/- for 2', max_length=30),
        ),
    ]
