# Generated by Django 5.0.2 on 2024-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0003_cuisine_data_tables_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tables_data',
        ),
    ]
