# Generated by Django 5.0.2 on 2024-03-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0004_delete_tables_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_accomodation_type', models.IntegerField()),
                ('table_status', models.CharField(default='Active', max_length=20)),
                ('table_owner', models.CharField(max_length=30)),
            ],
        ),
    ]
