# Generated by Django 5.0.2 on 2024-03-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0005_tables_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuisine_data',
        ),
    ]
