# Generated by Django 5.0.2 on 2024-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0006_delete_cuisine_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=30)),
                ('cuisine_image', models.ImageField(upload_to='uploads')),
                ('cuisine_type', models.CharField(max_length=50)),
                ('cuisine_price', models.BigIntegerField()),
                ('cuisine_status', models.CharField(max_length=10)),
                ('cuisine_restaurant_admin', models.CharField(max_length=30)),
            ],
        ),
    ]
