# Generated by Django 5.0.2 on 2024-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Main', '0009_alter_tables_data_table_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables_data',
            name='table_layout',
            field=models.IntegerField(null=True),
        ),
    ]
