# Generated by Django 5.0.2 on 2024-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin_Main", "0011_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="UserName",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
