# Generated by Django 5.0.2 on 2024-06-24 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Admin_Main", "0012_order_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="SelectedTableID",
            new_name="TableID",
        ),
    ]
