# Generated by Django 5.0.2 on 2024-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin_Main", "0013_rename_selectedtableid_order_tableid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="OrderStatus",
            field=models.CharField(default="Booked", max_length=50),
        ),
    ]
