# Generated by Django 5.0.2 on 2024-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin_Main", "0014_order_orderstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("EMail", models.CharField(max_length=50)),
                ("Message", models.CharField(max_length=500)),
            ],
        ),
    ]
